### ISSUE TITLE
Sleep Mode Freeze

### ISSUE THREAD

**Issue by TheGoldenShark** [cathery/sys-con#155]
The switch seems to be freezing to a black screen in sleep when animal crossing is open/suspended. This produces no fatal/crash report, but the switch won't respond to any input until the power button is held to force turn it off. The xbox 360 wireless adapter is being used, however it seemed to freeze without any controller connected.

It is very inconsistent, but can be reproduced by putting the switch to sleep while animal crossing is open, then waiting for a while.

The only other sysmodule installed is sys-clk, so I doubt it is a memory limitation.

The log from sys-con is in the pastebin below, but it doesn't look particularly useful.

https://pastebin.com/GfBgXmBy

Switch FW: 9.2.0
AMS: 0.10.5
Sys-Con: 0.5.3

**Comment by AuroraWright** [comment]
Can confirm, it also seems to cause random OS freezes (one every few days), seemingly when you open an applet/open the keyboard etc. If I had to guess, there's a memory leak somewhere.

**Comment by cathery** [comment]
This should hopefully be fixed in the next release. Probable cause: It takes so long to log to a file when controllers are being removed, that by the time it needs to actually remove the controller, all the other system modules are asleep, and sys-con waits indefinitely for them to respond, causing the whole system to freeze.

Also, I can't say I've ever experienced sys-con cause a freeze when opening applets. Maybe you're running too many sysmodules?

**Comment by cathery** [comment]
https://github.com/cathery/sys-con/releases/tag/v0.6.0
