### ISSUE TITLE
Xbox Elite Controller v2 Not Working

### ISSUE THREAD

**Issue by ghost** [cathery/sys-con#81]
I know this has been brought up in a few threads recently, but I thought it would help to have one with the controller name directly in the title ;p

I have an Xbox Elite Controller v2 that is recognized by the system as a USB controller, but no inputs are registered.
I've tried the new build as well as builds "jwliyq" and "ucmflq".

I also tried a regular Xbox One controller (with 3.5mm jack, no bluetooth), and that worked without any issues.

Here's my log. I've only ever plugged in the Elite Controller v2 and the regular Xbox One controller.
[log.txt](https://github.com/cathery/sys-con/files/3854835/log.txt)

If there's any other testing you need, let me know!

**Comment by Gonrak** [comment]
Same thing for me.
Controler appair instant (without L+R) but no input are recognized.

**Comment by z0oinks** [comment]
The Elite Controller now works as of the newest release. Also, I think there was a firmware update for the controller.

I guess you can consider this closed!

@Gonrak Try the new release and firmware update through the Accessories app on the Xbox One!

**Comment by cathery** [comment]
You're kidding me. The latest firmware update just broke Xbox One S controllers!

**Comment by z0oinks** [comment]
That's so weird... 
Try with the Elite 2 and report back? Maybe try the new release first without updating the firmware and see if it works. If it still doesn't, update the firmware and see if it works then?

I can at least say that the new firmware and the old release DOES NOT work.

**Comment by Gonrak** [comment]
My Switch is on ATM 8.1.0 + sys-con-051
And my controler Elite2 is on this lastest Firmware (v.4.8.1908.0), updated by the app "Xbox Accessory" on Windows 10 (v.300.1909.26004.0)

But still not working.

**Comment by z0oinks** [comment]
@Gonrak The latest firmware for the Elite v2 isn't available on the Windows 10 app. You have to use an Xbox to update it.

See the notes here: https://www.reddit.com/r/xboxinsiders/wiki/xgspreview/controllersupport

> The Xbox button on my controller takes me back to the Android home screen.
With a simple firmware update, the Xbox button will now pull up the Xbox guide so you can invite your friends to a party, view your achievements, and more. The on-screen Xbox button will still be there for controllers that don’t have an Xbox button equivalent, but now the Xbox controller will work the way it was designed.

In order to get the latest Firmware update for your controller on your Xbox One, you will first need to ensure you are on release OS Version 10.0.18363.8118 (19h1_release_xbox_dev_1911.191111-1430) or later. To validate your console OS version and instructions on how to get the update if you are not, please visit: Updating your Xbox One console

Once your Xbox One is ready, follow the steps here: Update your Xbox Wireless Controller to update your controller’s firmware.

If you are not prompted for the update immediately, open the Accessories app, select the [...] menu, then the top button will show your firmware version with "Update," select that option, then choose "update now."

Please note:

Update available through your Xbox now.

Update available through your PC coming soon.

**Comment by GhostlyCrowd** [comment]
Just wanted to say its working fine for me as well Elite V2 Firmware 4.8.1908.0 (latest)

**Comment by Gonrak** [comment]
Ok i found the solution.
You need to activate USB for PRO controller, in controller option section.
Now it's work for me.
